# Generated by Django 4.2.3 on 2023-07-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='razvozka',
            name='clr',
            field=models.CharField(default='', help_text='text color', max_length=30),
        ),
    ]
