# Generated by Django 4.2.3 on 2023-07-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0002_razvozka_clr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razvozka',
            name='clr',
        ),
    ]
