# Generated by Django 4.2.3 on 2023-07-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0003_remove_razvozka_clr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razvozka',
            name='date',
            field=models.DateField(help_text='date of transportation', null=True),
        ),
    ]
