# Generated by Django 4.2.3 on 2023-07-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0005_driver_alter_razvozka_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver.py',
            name='icon_code',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
