# Generated by Django 4.2.3 on 2023-07-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0006_driver_icon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver.py',
            name='icon_code',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='driver.py',
            name='phone1',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='driver.py',
            name='phone2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
