# Generated by Django 4.2.3 on 2023-07-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0007_alter_driver_icon_code_alter_driver_phone1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='icon_code',
            field=models.CharField(blank=True, default='icons/truck.svg', max_length=255, null=True),
        ),
    ]
