# Generated by Django 4.2.3 on 2023-07-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0008_alter_driver_icon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razvozka_returns',
            name='customer',
        ),
    ]
