# Generated by Django 4.2.3 on 2023-07-31 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0009_remove_razvozka_returns_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('icon_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='driver.py',
            name='icon_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='razv4_0.drivericons'),
        ),
    ]
