# Generated by Django 4.2.3 on 2023-07-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0010_drivericons_driver_icon_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver.py',
            name='icon_reference',
        ),
        migrations.AlterField(
            model_name='driver.py',
            name='icon_code',
            field=models.CharField(blank=True, default='razvozki4_0/icons/truck.svg', max_length=255, null=True),
        ),
    ]
