# Generated by Django 4.2.3 on 2023-07-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0011_remove_driver_icon_reference_alter_driver_icon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='icon_code',
            field=models.CharField(blank=True, default='icons/truck.svg', max_length=255, null=True),
        ),
    ]
