# Generated by Django 4.2.3 on 2023-08-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0014_alter_drivericons_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='razvozka_returns',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
