# Generated by Django 4.2.3 on 2023-08-05 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0016_remove_razvozka_return_goods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('mappoint', models.CharField(default='', help_text='Yandex mappoint', max_length=255)),
                ('subcontractor', models.BooleanField(default=False, help_text='True if subcontractor')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRazvozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='date of transportation')),
                ('date_id', models.SmallIntegerField(default=0, help_text='order inside date')),
                ('customer_name', models.CharField(help_text='customer as text could differ from db', max_length=100)),
                ('address', models.CharField(help_text='real address', max_length=255)),
                ('contact', models.CharField(help_text='real contacts', max_length=255)),
                ('to_do_deliver', models.CharField(help_text='things for delivery', max_length=255)),
                ('to_do_take', models.CharField(help_text='things to take from', max_length=255)),
                ('map_point', models.CharField(help_text='Yandex mappoint', max_length=255)),
                ('clr', models.CharField(default='', help_text='text color', max_length=30)),
                ('fulfilled', models.BooleanField(default=True, help_text='True is fulfilled')),
                ('deliver_to', models.BooleanField(default=False, help_text='transportation to processing')),
                ('return_from', models.BooleanField(default=False, help_text='return products from processing')),
                ('return_all', models.BooleanField(default=False, help_text='False if some part was not return')),
                ('date_until', models.DateField(blank=True, default='2022-08-01', help_text='plan (last) date of transportation', null=True)),
                ('date_create', models.DateField(blank=True, default='2022-08-01', help_text='date of create razvozka', null=True)),
                ('customer', models.ForeignKey(blank=True, help_text='customer base if exist', null=True, on_delete=django.db.models.deletion.SET_NULL, to='razv4_0.customer')),
                ('return_goods', models.ForeignKey(blank=True, help_text='from which delivery return', null=True, on_delete=django.db.models.deletion.SET_NULL, to='razv4_0.importrazvozka')),
            ],
        ),
    ]
