# Generated by Django 4.2.3 on 2023-08-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0018_alter_importrazvozka_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importrazvozka',
            name='customer',
        ),
    ]
