# Generated by Django 4.2.3 on 2023-08-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0020_importrazvozka_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='razvozka',
            name='return_close_date',
            field=models.DateField(null=True),
        ),
    ]
