# Generated by Django 4.2.3 on 2023-08-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razv4_0', '0021_driver_car_type_driver_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
